---
title: "Estimation of mean and SE"
author: "Viktoria Porolo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## Модель пациента: исследование прироста гемоглобина

```{r pressure, echo=FALSE}

true_p <- 0.6  # Истинная вероятность исцеления

```

## Однократная оценка по выборке

```{r sample_1}
n_patients <- 5  # Количество добровольцев 

group_recovery <- rbinom(n_patients, 1, true_p) # Генерация данных (исцеление — 1, не исцеление — 0)

print(group_recovery)

sample_p <- mean(group_recovery)

print(sample_p)

```

## Набираем статистику

```{r sample_n}
n_patients <- 5  # Количество добровольцев

n_repeats <- 1000  # Количество повторений эксперимента

df_all_repeats <- data.frame(
  n_exp = rep(1:n_repeats, each = n_patients),
  ID = rep(1:n_patients, n_repeats),
  recovery = rbinom(n_repeats * n_patients, 1, true_p)
)

```

## Оценка среднего в каждом эксперименте

```{r estimations}

df_sample_mean <- df_all_repeats %>% 
  group_by(n_exp) %>% 
  dplyr::summarise(mean_recovery = mean(recovery)) %>% 
  ungroup()

ggplot(df_sample_mean, aes(x = mean_recovery)) +
  geom_histogram(color = 'black', fill = 'white', binwidth = 0.2) +
  theme_bw()

```

## Количественные и качественные итоги

```{r conclusions}

error <- sqrt( mean((df_sample_mean$mean_recovery-true_p)^2) )
print(error)

```



